[package]
name = "tweet-like"
version = "0.1.0"
authors = ["saidgeek <me@saidgeek.land>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
